/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.poojan.GUI;

import com.poojan.model.DBManager;
import com.poojan.model.Product;
import com.poojan.model.Sale;
import java.text.DecimalFormat;
import java.util.List;
import java.util.Map;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import org.hibernate.HibernateException;

/**
 *
 * @author Poojan
 */
public class NewSaleGUI extends javax.swing.JFrame {

    public Sale sale;
    DBManager salesdb = new DBManager();

    /**
     * Creates new form NewSaleGUI
     */
    public NewSaleGUI() {
        initComponents();
        sale = new Sale();
        saveButton.setVisible(true);
        updateButton.setVisible(false);
        setUpTable();
        title.setText("New Sale");
        totalLabelIn.setVisible(false);
        totalLabel.setVisible(false);

        populateProductList();

    }

    public NewSaleGUI(Sale insale) {
        initComponents();
        // getting hibernate persisted version.
        this.sale = salesdb.getSaleBySale(insale.getId());
        
        saveButton.setVisible(false);
        title.setVisible(false);
        setUpTable();
        customerTextField.setText(sale.getName());
        
        outputTotal();

        populateProductList();

    }

    private void populateProductList() {
        List<Product> list = salesdb.getAllProducts();

        for (Product product : list) {
            productSelectionComboBox.addItem(product.getName());
        }
    }

    private void outputTotal() {
        totalLabelIn.setVisible(true);
        totalLabel.setVisible(true);
        float sum = sale.getTotalAmount();
        DecimalFormat df = new DecimalFormat("#.##");
        String out = df.format(sum);
        totalLabel.setText(out);
    }

    private void setUpTable() {

        Vector<String> tableHeaders = new Vector<String>();
        Vector tableData = new Vector();
        productsTable.setModel(new DefaultTableModel(tableData, tableHeaders));
        tableHeaders.add("Product");
        tableHeaders.add("Qty");
        tableHeaders.add("Sub Total");

        for (Map.Entry<Product, Integer> entry : sale.getMapProducts().entrySet()) {
            Product enterykey = entry.getKey();
            int val = entry.getValue();

            Vector<Object> oneRow = new Vector<Object>();

            oneRow.add(enterykey.getName());
            oneRow.add(val);
            oneRow.add(enterykey.getPrice() * val);
            tableData.add(oneRow);

        }

        productsTable.setModel(new DefaultTableModel(tableData, tableHeaders));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        title = new javax.swing.JLabel();
        productSelectionComboBox = new javax.swing.JComboBox<>();
        addProductButton = new javax.swing.JButton();
        saveButton = new javax.swing.JButton();
        pruductSelectedScrollPane = new javax.swing.JScrollPane();
        productsTable = new javax.swing.JTable();
        totalLabel = new javax.swing.JLabel();
        totalLabelIn = new javax.swing.JLabel();
        closeButton = new javax.swing.JButton();
        updateButton = new javax.swing.JButton();
        removeProductButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        customerTextField = new javax.swing.JFormattedTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        title.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N

        addProductButton.setText("Add");
        addProductButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addProductButtonActionPerformed(evt);
            }
        });

        saveButton.setText("Save & Close");
        saveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButtonActionPerformed(evt);
            }
        });

        productsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        productsTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                productsTableMouseClicked(evt);
            }
        });
        pruductSelectedScrollPane.setViewportView(productsTable);

        totalLabelIn.setText("Total");

        closeButton.setText("Close");
        closeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeButtonActionPerformed(evt);
            }
        });

        updateButton.setText("Update");
        updateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateButtonActionPerformed(evt);
            }
        });

        removeProductButton.setText("Remove");
        removeProductButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeProductButtonActionPerformed(evt);
            }
        });

        jLabel1.setText("Customer Name");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pruductSelectedScrollPane)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(productSelectionComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(addProductButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(removeProductButton)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(saveButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(updateButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(closeButton)))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 294, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(customerTextField)
                                .addContainerGap())
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(title)
                                    .addGap(208, 208, 208))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(totalLabelIn)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(totalLabel)
                                    .addContainerGap()))))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(title)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(productSelectionComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addProductButton)
                    .addComponent(removeProductButton)
                    .addComponent(jLabel1)
                    .addComponent(customerTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(pruductSelectedScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(totalLabel)
                    .addComponent(totalLabelIn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(saveButton)
                    .addComponent(closeButton)
                    .addComponent(updateButton))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addProductButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addProductButtonActionPerformed
        Product selectedProduct = getProductFromComboBox();

        sale.addProduct(selectedProduct);

        outputTotal();
        setUpTable();

    }//GEN-LAST:event_addProductButtonActionPerformed

    private Product getProductFromComboBox() {
        String name = productSelectionComboBox.getSelectedItem().toString();
        Product selectedProduct;
        selectedProduct = salesdb.getProductbyName(name);
        return selectedProduct;
    }

    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed

        if (setName()) {
            return;
        }
        try {
            salesdb.save(sale);
        } catch (HibernateException exc) {
            JOptionPane.showMessageDialog(rootPane, exc.getCause());
            System.out.println(exc);
            return;
        }
        setVisible(false);
        dispose();
    }//GEN-LAST:event_saveButtonActionPerformed

    private Boolean setName() {
        if (customerTextField.getText().length() < 5) {
            JOptionPane.showMessageDialog(rootPane, "Name is to Short.");
            return true;

        } else {
            sale.setName(customerTextField.getText());
        }
        return false;
    }

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed

    }//GEN-LAST:event_formWindowClosed

    private void closeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeButtonActionPerformed
        setVisible(false); //you can't see me!
        dispose(); //Destroy the JFrame object
    }//GEN-LAST:event_closeButtonActionPerformed

    private void updateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateButtonActionPerformed
        if (setName()) {
            return;
        }
        
        try {
            salesdb.update(sale);
        } catch (HibernateException exc) {
            JOptionPane.showMessageDialog(rootPane, exc.getCause());
            System.out.println(exc);
            return;
        }
        setVisible(false); //you can't see me!
        dispose(); //Destroy the JFrame object
    }//GEN-LAST:event_updateButtonActionPerformed

    private void removeProductButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeProductButtonActionPerformed
        Product selectedProduct = getProductFromComboBox();

        sale.removeProduct(selectedProduct);

        outputTotal();
        setUpTable();
    }//GEN-LAST:event_removeProductButtonActionPerformed

    private void productsTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_productsTableMouseClicked

        Object seleced = productsTable.getValueAt(productsTable.getSelectedRow(), 0);
        productSelectionComboBox.setSelectedItem(seleced);

    }//GEN-LAST:event_productsTableMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addProductButton;
    private javax.swing.JButton closeButton;
    private javax.swing.JFormattedTextField customerTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JComboBox<String> productSelectionComboBox;
    private javax.swing.JTable productsTable;
    private javax.swing.JScrollPane pruductSelectedScrollPane;
    private javax.swing.JButton removeProductButton;
    private javax.swing.JButton saveButton;
    private javax.swing.JLabel title;
    private javax.swing.JLabel totalLabel;
    private javax.swing.JLabel totalLabelIn;
    private javax.swing.JButton updateButton;
    // End of variables declaration//GEN-END:variables
}
