/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.poojan.GUI;

import com.poojan.model.DBManager;
import com.poojan.model.Product;
import com.poojan.model.Sale;
import java.util.Vector;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Poojan
 */
public class ViewSalesGUI extends javax.swing.JFrame {

    DBManager dBManager = new DBManager();

    /**
     * Creates new form ViewSalesGUI
     */
    public ViewSalesGUI() {
        initComponents();
        setUpTable();
    }

    private void setUpTable() {

        Vector<String> tableHeaders = new Vector<String>();
        Vector tableData = new Vector();
        tableHeaders.add("Sale ID");
        tableHeaders.add("Sale Date");
        tableHeaders.add("Sale Amount");

        for (Sale sale : dBManager.getAllSales()) {

            Vector<Object> oneRow = new Vector<Object>();
            oneRow.add(sale.getId());
            oneRow.add(sale.getSaleDate());
            oneRow.add(sale.getTotalAmount());
           

            tableData.add(oneRow);

        }
        
        salesTable.setModel(new DefaultTableModel(tableData, tableHeaders));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        salesTable = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                formFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                formFocusLost(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel1.setLabelFor(salesTable);
        jLabel1.setText("Sales");

        salesTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        salesTable.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                salesTableFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                salesTableFocusLost(evt);
            }
        });
        salesTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                salesTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(salesTable);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(165, 165, 165)
                .addComponent(jLabel1)
                .addContainerGap(187, Short.MAX_VALUE))
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 279, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void salesTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_salesTableMouseClicked
        
        Sale found = dBManager.getSaleBySale((int) salesTable.getValueAt(salesTable.getSelectedRow(), 0));
        new NewSaleGUI(found).setVisible(true);
        setUpTable();
        /*
        This 
        
         */
    }//GEN-LAST:event_salesTableMouseClicked

    private void salesTableFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_salesTableFocusGained
        setUpTable();
    }//GEN-LAST:event_salesTableFocusGained

    private void salesTableFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_salesTableFocusLost
        setUpTable();
    }//GEN-LAST:event_salesTableFocusLost

    private void formFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_formFocusGained

    }//GEN-LAST:event_formFocusGained

    private void formFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_formFocusLost

    }//GEN-LAST:event_formFocusLost


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable salesTable;
    // End of variables declaration//GEN-END:variables
}
