package com.poojan.GUI;

import com.poojan.model.DBManager;
import com.poojan.model.Sale;
import java.util.Vector;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Poojan
 */
public class ViewSalesGUI extends javax.swing.JFrame {

    DBManager dBManager = new DBManager();

    /**
     * Creates new form ViewSalesGUI
     */
    public ViewSalesGUI() {
        initComponents();
        setUpTable();
    }

    private void setUpTable() {
        
        Vector<String> tableHeaders = new Vector<String>();
        Vector tableData = new Vector();
        tableHeaders.add("Sale ID");
        tableHeaders.add("Name");
        tableHeaders.add("Sale Date");
        tableHeaders.add("Sale Amount");

        for (Sale sale : dBManager.getAllSales()) {

            Vector<Object> oneRow = new Vector<Object>();
            oneRow.add(sale.getId());
            oneRow.add(sale.getName());
            oneRow.add(sale.getSaleDate());
            oneRow.add(sale.getTotalAmount());

            tableData.add(oneRow);

        }

        salesTable.setModel(new DefaultTableModel(tableData, tableHeaders));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titleLabel = new javax.swing.JLabel();
        salesScrollPane = new javax.swing.JScrollPane();
        salesTable = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(500, 400));
        addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                formFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                formFocusLost(evt);
            }
        });

        titleLabel.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        titleLabel.setLabelFor(salesTable);
        titleLabel.setText("Sales");

        salesScrollPane.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                salesScrollPaneFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                salesScrollPaneFocusLost(evt);
            }
        });

        salesTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        salesTable.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                salesTableFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                salesTableFocusLost(evt);
            }
        });
        salesTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                salesTableMouseClicked(evt);
            }
        });
        salesScrollPane.setViewportView(salesTable);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(200, 200, 200)
                .addComponent(titleLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(salesScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(titleLabel)
                .addGap(18, 18, 18)
                .addComponent(salesScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 346, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void salesTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_salesTableMouseClicked

        Sale found = dBManager.getSaleBySale((int) salesTable.getValueAt(salesTable.getSelectedRow(), 0));
        new NewSaleGUI(found).setVisible(true);
        setUpTable();
        /*
        This 
        
         */
    }//GEN-LAST:event_salesTableMouseClicked

    private void salesTableFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_salesTableFocusGained
        setUpTable();
    }//GEN-LAST:event_salesTableFocusGained

    private void salesTableFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_salesTableFocusLost
        setUpTable();
    }//GEN-LAST:event_salesTableFocusLost

    private void formFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_formFocusGained

    }//GEN-LAST:event_formFocusGained

    private void formFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_formFocusLost

    }//GEN-LAST:event_formFocusLost

    private void salesScrollPaneFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_salesScrollPaneFocusGained

    }//GEN-LAST:event_salesScrollPaneFocusGained

    private void salesScrollPaneFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_salesScrollPaneFocusLost

    }//GEN-LAST:event_salesScrollPaneFocusLost


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane salesScrollPane;
    private javax.swing.JTable salesTable;
    private javax.swing.JLabel titleLabel;
    // End of variables declaration//GEN-END:variables
}
